version: "3.3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/code
  service:
    image: jonbri/random-service_service
    # build: ../random-service
    volumes:
      - .:/code